### ISSUE TITLE
Database name and the structure of input and output documents for Bayesian SEIR and Intercity Models

### ISSUE THREAD

**Issue by risavkarna** [covidsimteam/py-core#3]
- [x] Please write the name of the couchdb database you are posting your output into e.g. `covidsimteam` or `seir` or `internode`.

- [x] Please write the json document structure for the input data for each of the models

- [x] Please write the json document structure for the output data for each of the models

The data input and output should be minimal and normalized sensibly 

i.e. do not have anything but the the keys as fields and do not store any redundant data. 

e.g. if you have infected population count and total population, do not store percentage of infected population as this data is easily derived from the existing data.

**Comment by aayushkafle** [comment]
I have used two databases and the document can be found at: https://github.com/covidsimteam/py-core/tree/develop/intercity
